apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cm-propagation-test
  name: cm-propagation-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cm-propagation-test
  strategy: {}
  template:
    metadata:
      labels:
        app: cm-propagation-test
    spec:
      volumes:
        - name: cm-volume
          configMap:
            name: my-test
      containers:
      - image: ubi8
        name: ubi8
        command:
          - sleep
          - infinity
        volumeMounts:
          - mountPath: /tmp/my-test
            name: cm-volume
        envFrom:
          - configMapRef:
              name: my-test

